apiVersion:  v1
kind:  Service
metadata:
  name:  myapp-tomcat-service
  labels:
    app:  service-app
    tier: front-end
spec:
  type:  LoadBalancer
  ports:
    - targetPort:  80
      port:  80
      #nodePort: 30012
  selector:
     app:  myapp
     tier:  front-end
